### ISSUE TITLE
Union Types?

### ISSUE THREAD

**Issue by MatthewPatience** [remind101/AutoGraph#107]
Are union types supported and if so, how would I go about doing them?

So for example, if I had a request of:

```
query GetItems {
     item {
          ... on SuperItems {
               id
               name
          }
          ... on SuperDuperItem {
               id
               name
          }
     }
}
```

How would I specify this in the Query Document, and also in parsed model?

Thanks!

**Comment by rex-remind101** [comment]
What you're referring to are inline fragments https://graphql.org/learn/queries/#inline-fragments

from memory I think this should work
```
...
Selection.field(name: "item", alias: nil, arguments: nil, directives: nil, type: .object(selectionSet: [
    Selection.inlineFragment(namedType: "SuperItems", directives: nil, selectionSet: [
        Selection.field(name: "id", alias: nil, arguments: nil, directives: nil, type: .scalar),
        Selection.field(name: "name", alias: nil, arguments: nil, directives: nil, type: .scalar)
    ]),
    Selection.inlineFragment(namedType: "SuperDuperItem", directives: nil, selectionSet: [
        Selection.field(name: "id", alias: nil, arguments: nil, directives: nil, type: .scalar),
        Selection.field(name: "name", alias: nil, arguments: nil, directives: nil, type: .scalar)
    ])
])
...
```
Could do `Object` instead of `Selection.field(... type: .object...)` etc. for these instead too and should work and be less boilerplate and provide default `nil` values for a lot of the args; this example is just what my memory served me quickly.

FYI, our code generator (written entirely in Swift) has been stable for a while now, in the process of cleaning it up and getting CI/deployments for it. Targeting before EOY so, hopefully soon, you won't need to think about these details anymore.

**Comment by MatthewPatience** [comment]
@rex-remind101 That's awesome, can't wait for the code generator! We had moved away from Apollo though because of it's code generation, mainly because we wanted to specify our own models. How does the code generation work for AutoGraph? Does it generate models and the request like Apollo, or will it allow us to use our own pre-built models with a generated request?

**Comment by MatthewPatience** [comment]
Also, the inline fragments make sense, however I was referring to something else called union types: (https://graphql.org/learn/schema/) You'll have to search the page for "Union Types"

How to specify the inline fragments in the request makes sense, but the issue I'm having is trying to specify is how to represent the union type in the response. At request time, it is not known if "item" will be of type "SuperItem" or "SuperDuperItem". It's basically a generic item type. When it is returned it will be one of the specified union types, which the response handler will know typically by the context of some other value in the parent object. In this case let's pretend the request is actually:

```
query GetItems {
     items(first: 10)
          type
          item {
              ... on SuperItem {
                    id
                    name
               }
               ... on SuperDuperItem {
                    id
                    name
               }
          }
     }
}
```

In this example "item" can be of either type SuperItem or SuperDuperItem, and the response handler will know based on the value of the "type" field.

Now I know there isn't any way to specify in Swift that "item" can be one of many types, but is there a way to specify that it is a raw JSON object that can be parsed manually after the response returns from GraphQL?

**Comment by rex-remind101** [comment]
Union types are opaque to a query, you can only use Inline Fragments to access them. Therefore the shape of the JSON isn't going to be specialized for union types, it will be JSON matching the query shape.

However by "response", _I think_ you actually mean the "mapping" portion _after_ the response is returned by the server? In which case, "is there a way to specify that it is a raw JSON object that can be parsed manually after the response returns from GraphQL?" I think you need to clarify what you mean here.

If what you mean is "can I just get back the JSON", then yes. Make a `Decodable` data structure that simply captures the returned JSON on a property, and use that as your `SerializedObject` for your [Request](https://github.com/remind101/AutoGraph/blob/master/AutoGraph/Request.swift#L7)

If this isn't what you meant then maybe an example of what you want at the call site would help illustrate it.

"How does the code generation work for AutoGraph? Does it generate models and the request like Apollo, or will it allow us to use our own pre-built models with a generated request?"
It generates structs and maps response data directly to them in a safe way, Apollo passes around Dictionaries internally which we're not fans of. You can use those structs however you please, including mapping them to your own models. If you're asking if you can make a model and we'll adhere directly to that, it sounds somewhat like having a meta-programming abstraction that can arbitrarily map to any model, which isn't really practical since Swift doesn't support first class meta-programming (...yet). If you had something more specific in mind though I'd love to hear it.

Also, the code generator is a SPM package/binary written entirely in Swift, which is much more to our liking. Swift happens to be a great language for writing compiler-like software.

**Comment by MatthewPatience** [comment]
You are completely correct on the union types, my lack of GQL experience is showing ;-)

I am referring to the mapping portion as you said, and it's specifically about when you have an unknown nested type within the response object. I figured out the solution though, it was simply to set the nested type as a Dictionary. Thanks for your help and quick responses.

In regards to the code generation, I do have some thoughts. It's the auto generated structs that are concerning, because it would mean that if we want to use our own internal models, we would have to write a parser for each of the structs, especially becoming more complicated if the structs are request specific like in Apollo. My thought would be to have requests that are auto-generated, but have the response still come out as JSON so that we could map to our own internal Codable models, or allow a return type to be passed in to the generated function just like you have now.

**Comment by rex-remind101** [comment]
The code generator isn't mandatory so it shouldn't affect you if you don't want to use it.

**Comment by MatthewPatience** [comment]
That's fair, thanks again for the library and all your work!
