### ISSUE TITLE
QUESTION: Is it possible to map InlineFragments in v0.8.0?

### ISSUE THREAD

**Issue by kerryknight** [remind101/AutoGraph#108]
Hi!

Great repo, thanks for sharing!  This might be a shot in the dark as my question pertains to an old version of AutoGraph, so feel free to say you can't help.  

I'm using v0.8.0 (we utilize Realm integration so aren't in a position to upgrade just yet to 0.9.0) and am trying to figure out the proper way to set up `mappingKeys` on my `Request` object for inline fragments.  I am able to build and send my request fine with `InlineFragment` objects but I'm failing to come up with what feels like the correct way to map/parse the response.  Issue #107 came close to answering my question, but I'm wondering if there's a more proper way of handling the mapping (via `mappingKeys`) instead of doing it all manually from the raw json response?

Example query:
```
query getFeed {
    id
    blocks {
      __typename
      id
      ... on BlockTypeOne {
        title
      }
      ... on BlockTypeTwo {
        message
        userName
      }
    }
}
```

My attempt at `mappingKeys`:
```
var mappingKeys: Set<FeedKey> = [
  .id,
  .blocks([
      .typename,
      .id
      .title,
      .message,
      .username
    })
]
```
Since the 2 inline fragments have different fields, I'm trying to figure out a "correct" way to set up my `mappingKeys`.  Using the above example, if I try to include `title`, `message` and `userName` at all times in the `Request` object's `mappingKeys`, I end up with a `Crust.MappingError.noDataAtKeyPathFromKeyToMapFrom(keyPath:key:)` error in Crust as all values are not present on all response objects.  Again, I realize my question involves a legacy version that includes old dependencies, but I thought I'd ask.  At worst, I can probably just take the root json response and map everything the old fashioned way by hand.

Thanks again for your time and the great repo!

**Comment by rex-remind101** [comment]
Crust implicitly expects every value to exist for every MappingKey, just like Codable expects every value to exist for every CodingKey, just like Swift expects full initialization. If what you want is a field to not be mapped to because the value is not there, even though a key exists for it, that's a semantic contradiction.

In your `Mapping` implementation you'll need to do the `__typename` checking yourself then for value existence and then map the appropriate keys. I've debated adding a `IgnoreMissingValueMappingKey` but I think it sends the wrong signal so decided not to go down that route long ago.

The additional option, which I think is the better one, is to structure your code so that `BlockTypeOne` and `BlockTypeTwo` are two separate substructures of the `blocks` object, with their own mappings. You still have to check on `__typename` but it's clearer from data shape as to why. This leans in more naturally to the impedance mismatch between Swift and GraphQL.

**Comment by kerryknight** [comment]
Thank you so much for your detailed response.  From the sound of it, I'm going to have to do the majority of the mapping manually based on the `__typename` check.  I failed to mention that my `blocks` object is actually an array, which is populated by different object types ("different" insofar as they are denoted differently by the value of their respective `__typename`) each with their own set of keys.  Thus, it sounds like your second proposed option of using substructures is out.  

I'm going to close this with the assumption I indeed am going to have to parse/map everything the long way by hand directly from the JSON.  It's what I was afraid of originally, but wasn't 100% sure if maybe I'd missed something when setting up my `Request` and `Mapping` objects if there were some way to conditionally map keys from the response.  If I come up with a concise way of doing it, I'll be certain to report back here for reference.

Thanks again for taking the time to respond, I really appreciate it!
