### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by explicitcall** [remind101/AutoGraph#69]
Hi, are there any plans to add Swift 4 support for this library? Thanks.

**Comment by rex-remind101** [comment]
Yes, thanks for asking. First https://github.com/rexmas/JSONValue and https://github.com/rexmas/Crust will need some updating too. I can work on that this week. I'll let you know if it takes longer than the end of the week.

**Comment by rex-remind101** [comment]
Update:

* JSONValueRX was easy to update to Swift 4. It was source compatible from the start, I made some nicer syntactic adjustments and bumped the major version and released an new CocoaPod.

* Crust has been more challenging to deal with. Seems like existential class types don't behave exactly like subtypes to their base class types, at least with `inout` parameters. I'd expect `NSNumber & RLMInt` to be a subtype of `NSNumber` but it's failing where I attempt to pass the former into the later in the mapping operator (`<-`). You can see this below
<img width="1134" alt="screen shot 2017-10-13 at 11 23 43 pm" src="https://user-images.githubusercontent.com/4573957/31573407-c184aa06-b06f-11e7-8c13-4223a5005947.png">
Per the example, it does appear that doing a little bit of indirection through a local variable type checks. So I think I can maybe overload the `<-` operator with a `NSNumber & RLM<Type>` for all RLM types and get this to work appropriately.

* Next issue I ran into is whether RealmSwift, which is used for testing (and by us at Remind), is compatible with Swift 4. Looks like if you build from binary it is, but our goal is to support CocoaPods without any extra steps. I asked if it's source compatible with Swift 4 [here](https://stackoverflow.com/questions/44640852/how-can-i-use-realm-with-swift-4/44641478?noredirect=1#comment80429251_44641478) and waiting for a reply.

* Finally, AutoGraph is currently reliant on [Alamofire](https://github.com/Alamofire/Alamofire). I had assumed that Alamofire supports Swift 4 already, but I was wrong. Looks like they will for their 5.0 release, but this [pr](https://github.com/Alamofire/Alamofire/pull/2315) also makes it sound like version 4.5.1 is source compatible with Swift 4 anyway, so I'll give that a shot.

Things are looking mostly good it seems, I'll keep hacking away at this over the next few days. if updating via CocoaPods for Swift 4 isn't a smooth transition because of the above dependency issues I'll make a `swift-4` branch separately with specific directions on how to get that working.

Once [swift version support](https://github.com/CocoaPods/CocoaPods/issues/7134) is released for CocoaPods this should be less of an issue.

**Comment by rex-remind101** [comment]
Opened a pr for Swift 4 to Crust https://github.com/rexmas/Crust/pull/78

**Comment by rex-remind101** [comment]
Waiting on review for https://github.com/remind101/AutoGraph/pull/71, will then update the pod to swift 4. Should happen tomorrow. There's been some source breaking changes fyi, but nothing too crazy.

**Comment by rex-remind101** [comment]
releases 0.4.0 supports swift 4
